### ISSUE TITLE
Service/Service (ServiceD69D759B) Resource timed out waiting for completion (RequestToken: 236aecf9-3036-3527-ad2e-213c52aed71e)

### ISSUE THREAD

**Issue by zstartw** [aws-samples/aws-ocpp-gateway#44]
Our company has deployed the iot service based on the mqtt protocol before, and now the charging pile needs to support ocpp. I tried it according to the process you wrote, but something went wrong, please help me to take a look

When the following code is executed, an error is reported

```
npx cdk deploy
```

and the following is the error log.

```
AwsOcppGatewayStack | 10:19:35 | CREATE_FAILED        | AWS::ECS::Service                           | Service/Service (ServiceD69D759B) Resource timed out waiting for completion (RequestToken: 236aecf9-3036-3527-ad2e-213c52aed71e)

 ❌  AwsOcppGatewayStack failed: Error: The stack named AwsOcppGatewayStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource timed out waiting for completion (Requ
estToken: 236aecf9-3036-3527-ad2e-213c52aed71e)
    at FullCloudFormationDeployment.monitorDeployment (E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:380:10236)
    at runMicrotasks (<anonymous>)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:383:145775)
    at async E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:383:128776
    at async run (E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:383:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named AwsOcppGatewayStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource timed out waitig for completion (RequestToken: 236aecf9-3036-3527-ad2e-213c52aed71e)
ng for completion (RequestToken: 236aecf9-3036-3527-ad2e-213c52aed71e)
    at deployStacks (E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:383:129083)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdkToolkit.deploy (E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:383:147824)
    at async exec4 (E:\MyAndroidProject\GitHub\aws-ocpp-gateway\node_modules\aws-cdk\lib\index.js:438:51984)

Stack Deployments Failed: Error: The stack named AwsOcppGatewayStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource timed out waiting for completion (RequestToken: 236aecf9-3036-3527-ad2e-213c52aed71e)
```

This is my current operating environment
System: Windows 10
docker: 20.10.17
npx: 8.11.0
cdk: 2.84.0
nodejs: 16.16.0
Operating environment: visual studio code terminal

**Comment by zstartw** [comment]
By checking the cluster background log, I found that the following error has been reported


<html>
<body>


2023/6/19 GMT+8 14:36:17 | /bin/sh: line 1: /opt/ocpp-gateway/run-server.sh: cannot execute: required file not found | dcf2ec0196064d8084f8df380c2b428e | Container
-- | -- | -- | --
2023/6/19 GMT+8 14:35:07 | /bin/sh: line 1: /opt/ocpp-gateway/run-server.sh: cannot execute: required file not found | d3e976899ed54c1991a2eef59ecd5007 | Container
2023/6/19 GMT+8 14:33:58 | /bin/sh: line 1: /opt/ocpp-gateway/run-server.sh: cannot execute: required file not found | 7c850ac7430647019a28252c632374b7 | Container


</body>
</html>

**Comment by zstartw** [comment]
I found that it was a problem with the run-server.sh file format, the file edited under window would not be found in Linux, I used visual studio code, changed CRLF to LF, and the problem was solved
